//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG.OA.Model.OAModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinitionIdentityTable
    {
        public long SurrogateIdentityId { get; set; }
        public System.Guid DefinitionIdentityHash { get; set; }
        public System.Guid DefinitionIdentityAnyRevisionHash { get; set; }
        public string Name { get; set; }
        public string Package { get; set; }
        public Nullable<long> Build { get; set; }
        public Nullable<long> Major { get; set; }
        public Nullable<long> Minor { get; set; }
        public Nullable<long> Revision { get; set; }
    }
}
