//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG.OA.Model.OAModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OADBContext : DbContext
    {
        public OADBContext()
            : base("name=OADBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionInfo> ActionInfo { get; set; }
        public DbSet<FileInfo> FileInfo { get; set; }
        public DbSet<MenuInfo> MenuInfo { get; set; }
        public DbSet<OrderInfo> OrderInfo { get; set; }
        public DbSet<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public DbSet<RoleInfo> RoleInfo { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<UserInfoExt> UserInfoExt { get; set; }
        public DbSet<WF_Instance> WF_Instance { get; set; }
        public DbSet<WF_Step> WF_Step { get; set; }
        public DbSet<WF_Temp> WF_Temp { get; set; }
        public DbSet<DefinitionIdentityTable> DefinitionIdentityTable { get; set; }
        public DbSet<IdentityOwnerTable> IdentityOwnerTable { get; set; }
        public DbSet<InstanceMetadataChangesTable> InstanceMetadataChangesTable { get; set; }
        public DbSet<InstancePromotedPropertiesTable> InstancePromotedPropertiesTable { get; set; }
        public DbSet<InstancesTable> InstancesTable { get; set; }
        public DbSet<KeysTable> KeysTable { get; set; }
        public DbSet<LockOwnersTable> LockOwnersTable { get; set; }
        public DbSet<RunnableInstancesTable> RunnableInstancesTable { get; set; }
        public DbSet<ServiceDeploymentsTable> ServiceDeploymentsTable { get; set; }
    }
}
