//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG.OA.Model.OAModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunnableInstancesTable
    {
        public long SurrogateInstanceId { get; set; }
        public Nullable<System.Guid> WorkflowHostType { get; set; }
        public Nullable<long> ServiceDeploymentId { get; set; }
        public System.DateTime RunnableTime { get; set; }
        public long SurrogateIdentityId { get; set; }
    }
}
